apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: webapp
    repoURL: 'https://github.com/takytaky/webapp-config'
    targetRevision: master
  project: cicd
  syncPolicy:
    automated: 
      prune: true      # Git에서 삭제된 리소스를 클러스터에서도 삭제
      selfHeal: true   # 클러스터 리소스가 수동으로 수정되면 Git 상태로 복구
    syncOptions:
      - CreateNamespace=true
      
