apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CICD Project
  sourceRepos:
  - 'https://github.com/takytaky/webapp-config.git'

  destinations:
  - namespace: default
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
